services:
  api:
    container_name: 'LindaForumEngine'
    build: ./
    links:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    restart: always
    container_name: forum-engine-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lxqtpr2021
    volumes:
      - ./src/main/resources/db/changelog/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/postgres
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lxqtpr@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lxqtpr2021
    ports:
      - "5050:80"

volumes:
  db-data: