server:
  servlet:
    context-path: "/api/v1"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/lindaforumengine
    username: postgres
    password: lxqtpr2021
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: validate
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
security:
  jwt:
    accessSecret: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
    refreshSecret: "zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg=="
    accessExpirationInMinutes: 5
    refreshExpirationInMinutes: 43200